Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pudb/__init__.py", line 93, in runscript
    dbg._runscript(mainpyfile)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 429, in _runscript
    self.run(statement, globals=globals_, locals=locals_)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "test.py", line 2, in <module>
    import tree
  File "test.py", line 2, in <module>
    import tree
  File "/usr/lib/python2.7/bdb.py", line 49, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 160, in dispatch_line
    self.user_line(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 381, in user_line
    self.interaction(frame)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 349, in interaction
    show_exc_dialog=show_exc_dialog)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2084, in call_with_ui
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2322, in interaction
    self.event_loop()
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 2288, in event_loop
    toplevel.keypress(self.size, k)
  File "/usr/local/lib/python2.7/dist-packages/pudb/ui_tools.py", line 96, in keypress
    result = self._w.keypress(size, key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 2269, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/usr/local/lib/python2.7/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/local/lib/python2.7/dist-packages/pudb/ui_tools.py", line 101, in keypress
    return handler(self, size, key)
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 1076, in next
    end()
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 1068, in end
    self.debugger.save_breakpoints()
  File "/usr/local/lib/python2.7/dist-packages/pudb/debugger.py", line 240, in save_breakpoints
    if not bp.temporary])
  File "/usr/local/lib/python2.7/dist-packages/pudb/settings.py", line 515, in save_breakpoints
    histfile = open(get_breakpoints_file_name(), 'w')
IOError: [Errno 13] 权限不够: '/home/sarahzhou/.config/pudb/saved-breakpoints-2.7'
